export const RECEIVE_STORAGE_PALCE_LIST = 'receive_storage_place_list';
export const LOADING_STORAGE_PALCE_LIST = 'loading_storage_place_list';
export const area = [
    { code: 'A' },
    { code: 'B' },
    { code: 'C' },
    { code: 'D' },
    { code: 'E' },
    { code: 'F' },
    { code: 'G' },
    { code: 'H' },
    { code: 'I' },
    { code: 'J' },
    { code: 'K' },
    { code: 'L' },
    { code: 'M' },
    { code: 'N' },
    { code: 'O' },
    { code: 'P' },
    { code: 'Q' },
    { code: 'R' },
    { code: 'S' },
    { code: 'T' },
    { code: 'U' },
    { code: 'V' },
    { code: 'W' },
    { code: 'X' },
    { code: 'Y' },
    { code: 'Z' },
];
