export const CHANNEL_INFO_TYPE = "CHANNEL_INFO";
export const HANDLE_CHANGE_DATA = "HANDLE_CHANGE_DATA";
export const ADD_ITEM_DATA = "ADD_ITEM_DATA";
export const MOVE_ITEM_DATA = "MOVE_ITEM_DATA";

export const CHANGE_SIGN_DATA = "CHANGE_SIGN_DATA";
export const ADD_SIGN_DATA = "ADD_SIGN_DATA";
export const MOVE_SIGN_DATA = "MOVE_SIGN_DATA";

export const CHANGE_THIRD_DATA = "CHANGE_THIRD_DATA";
export const ADD_THIRD_DATA = "ADD_THIRD_DATA";
export const MOVE_THIRD_DATA = "MOVE_THIRD_DATA";

export const CHANGE_TRUCKING_DATA = "CHANGE_TRUCKING_DATA";
export const ADD_TRUCKING_DATA = "ADD_TRUCKING_DATA";
export const MOVE_TRUCKING_DATA = "MOVE_TRUCKING_DATA";
