export const APPORTION_COST_DATA = "APPORTION_COST_DATA";
export const OPERATION_COST_DATA = "OPERATION_COST_DATA";
export const LISTING_COST_DATA = "LISTING_COST_DATA";
export const TRANSPORT_COST_DATA = "TRANSPORT_COST_DATA";