const emotionData = [
    {
        title: 'Smile',
        entity: '/:000',
        meaning: '[Smile]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/0fixed.png',
    },
    {
        title: 'Shy',
        entity: '/:001',
        meaning: '[Shy]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/1fixed.png',
    },
    {
        title: 'Tongue',
        entity: '/:002',
        meaning: '[Tongue]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/2fixed.png',
    },
    {
        title: 'Titter',
        entity: '/:003',
        meaning: '[Titter]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/3fixed.png',
    },
    {
        title: 'Admire',
        entity: '/:004',
        meaning: '[Admire]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/4fixed.png',
    },
    {
        title: 'Risus',
        entity: '/:005',
        meaning: '[Risus]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/5fixed.png',
    },
    {
        title: 'Dance',
        entity: '/:006',
        meaning: '[Dance]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/6fixed.png',
    },
    {
        title: 'Blow a Kiss',
        entity: '/:007',
        meaning: '[Blow a Kiss]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/7fixed.png',
    },
    {
        title: 'Comfort',
        entity: '/:008',
        meaning: '[Comfort]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/8fixed.png',
    },
    {
        title: 'Hug',
        entity: '/:009',
        meaning: '[Hug]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/9fixed.png',
    },
    {
        title: 'Put on steam',
        entity: '/:010',
        meaning: '[Put on steam]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/10fixed.png',
    },
    {
        title: 'Victory',
        entity: '/:011',
        meaning: '[Victory]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/11fixed.png',
    },
    {
        title: 'Strong',
        entity: '/:012',
        meaning: '[Strong]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/12fixed.png',
    },
    {
        title: 'Kiss',
        entity: '/:013',
        meaning: '[Kiss]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/13fixed.png',
    },
    {
        title: 'Anthomaniac',
        entity: '/:014',
        meaning: '[Anthomaniac]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/14fixed.png',
    },
    {
        title: 'Grin',
        entity: '/:015',
        meaning: '[Grin]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/15fixed.png',
    },
    {
        title: 'Seek',
        entity: '/:016',
        meaning: '[Seek]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/16fixed.png',
    },
    {
        title: 'Call out',
        entity: '/:017',
        meaning: '[Call out]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/17fixed.png',
    },
    {
        title: 'Cast accounts',
        entity: '/:018',
        meaning: '[Cast accounts]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/18fixed.png',
    },
    {
        title: 'Miser',
        entity: '/:019',
        meaning: '[Miser]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/19fixed.png',
    },
    {
        title: 'Good idea',
        entity: '/:020',
        meaning: '[Good idea]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/20fixed.png',
    },
    {
        title: 'Grimace',
        entity: '/:021',
        meaning: '[Grimace]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/21fixed.png',
    },
    {
        title: 'Angel',
        entity: '/:022',
        meaning: '[Angel]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/22fixed.png',
    },
    {
        title: 'Good bye',
        entity: '/:023',
        meaning: '[Good bye]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/23fixed.png',
    },
    {
        title: 'Drool',
        entity: '/:024',
        meaning: '[Drool]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/24fixed.png',
    },
    {
        title: 'Enjoy',
        entity: '/:025',
        meaning: '[Enjoy]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/25fixed.png',
    },
    {
        title: 'Erotomania',
        entity: '/:026',
        meaning: '[Erotomania]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/26fixed.png',
    },
    {
        title: 'Dumbstruck',
        entity: '/:027',
        meaning: '[Dumbstruck]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/27fixed.png',
    },
    {
        title: 'Thinking',
        entity: '/:028',
        meaning: '[Thinking]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/28fixed.png',
    },
    {
        title: 'Puzzle',
        entity: '/:029',
        meaning: '[Puzzle]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/29fixed.png',
    },
    {
        title: 'Query',
        entity: '/:030',
        meaning: '[Query]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/30fixed.png',
    },
    {
        title: 'No money',
        entity: '/:031',
        meaning: '[No money]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/31fixed.png',
    },
    {
        title: 'Bored',
        entity: '/:032',
        meaning: '[Bored]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/32fixed.png',
    },
    {
        title: 'Suspect',
        entity: '/:033',
        meaning: '[Suspect]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/33fixed.png',
    },
    {
        title: 'Hush',
        entity: '/:034',
        meaning: '[Hush]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/34fixed.png',
    },
    {
        title: 'Complacent',
        entity: '/:035',
        meaning: '[Complacent]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/35fixed.png',
    },
    {
        title: 'Shake head',
        entity: '/:036',
        meaning: '[Shake head]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/36fixed.png',
    },
    {
        title: 'Cold',
        entity: '/:037',
        meaning: '[Cold]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/37fixed.png',
    },
    {
        title: 'Awkward',
        entity: '/:038',
        meaning: '[Awkward]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/38fixed.png',
    },
    {
        title: 'Smirk',
        entity: '/:039',
        meaning: '[Smirk]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/39fixed.png',
    },
    {
        title: 'Amazed',
        entity: '/:040',
        meaning: '[Amazed]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/40fixed.png',
    },
    {
        title: 'However',
        entity: '/:041',
        meaning: '[However]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/41fixed.png',
    },
    {
        title: 'Sweat',
        entity: '/:042',
        meaning: '[Sweat]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/42fixed.png',
    },
    {
        title: 'Loneliness',
        entity: '/:043',
        meaning: '[Loneliness]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/43fixed.png',
    },
    {
        title: 'Sleepy',
        entity: '/:044',
        meaning: '[Sleepy]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/44fixed.png',
    },
    {
        title: 'Faint',
        entity: '/:045',
        meaning: '[Faint]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/45fixed.png',
    },
    {
        title: 'Distressed',
        entity: '/:046',
        meaning: '[Distressed]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/46fixed.png',
    },
    {
        title: 'Grievance',
        entity: '/:047',
        meaning: '[Grievance]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/47fixed.png',
    },
    {
        title: 'Sob',
        entity: '/:048',
        meaning: '[Sob]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/48fixed.png',
    },
    {
        title: 'Cry',
        entity: '/:049',
        meaning: '[Cry]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/49fixed.png',
    },
    {
        title: 'Wail',
        entity: '/:050',
        meaning: '[Wail]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/50fixed.png',
    },
    {
        title: 'Obey',
        entity: '/:051',
        meaning: '[Obey]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/51fixed.png',
    },
    {
        title: 'Sorry',
        entity: '/:052',
        meaning: '[Sorry]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/52fixed.png',
    },
    {
        title: 'Bye',
        entity: '/:053',
        meaning: '[Bye]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/53fixed.png',
    },
    {
        title: 'Frown',
        entity: '/:054',
        meaning: '[Frown]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/54fixed.png',
    },
    {
        title: 'So tired',
        entity: '/:055',
        meaning: '[So tired]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/55fixed.png',
    },
    {
        title: 'Fall ill',
        entity: '/:056',
        meaning: '[Fall ill]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/56fixed.png',
    },
    {
        title: 'Vomit',
        entity: '/:057',
        meaning: '[Vomit]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/57fixed.png',
    },
    {
        title: 'Fall on evil days',
        entity: '/:058',
        meaning: '[Fall on evil days]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/58fixed.png',
    },
    {
        title: 'Surprised',
        entity: '/:059',
        meaning: '[Surprised]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/59fixed.png',
    },
    {
        title: 'Stunned',
        entity: '/:060',
        meaning: '[Stunned]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/60fixed.png',
    },
    {
        title: 'Shut up',
        entity: '/:061',
        meaning: '[Shut up]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/61fixed.png',
    },
    {
        title: 'Due to flat',
        entity: '/:062',
        meaning: '[Due to flat]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/62fixed.png',
    },
    {
        title: 'Despise you',
        entity: '/:063',
        meaning: '[Despise you]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/63fixed.png',
    },
    {
        title: 'Rage',
        entity: '/:064',
        meaning: '[Rage]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/64fixed.png',
    },
    {
        title: 'Angry',
        entity: '/:065',
        meaning: '[Angry]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/65fixed.png',
    },
    {
        title: 'Mammon',
        entity: '/:066',
        meaning: '[Mammon]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/66fixed.png',
    },
    {
        title: 'Learn from lei feng',
        entity: '/:067',
        meaning: '[Learn from lei feng]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/67fixed.png',
    },
    {
        title: 'Wishing you prosperity',
        entity: '/:068',
        meaning: '[Wishing you prosperity]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/68fixed.png',
    },
    {
        title: 'Waiter',
        entity: '/:069',
        meaning: '[Waiter]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/69fixed.png',
    },
    {
        title: 'Boss',
        entity: '/:070',
        meaning: '[Boss]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/70fixed.png',
    },
    {
        title: 'Evil',
        entity: '/:071',
        meaning: '[Evil]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/71fixed.png',
    },
    {
        title: 'Challenge',
        entity: '/:072',
        meaning: '[Challenge]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/72fixed.png',
    },
    {
        title: 'CS',
        entity: '/:073',
        meaning: '[CS]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/73fixed.png',
    },
    {
        title: 'Invisible man',
        entity: '/:074',
        meaning: '[Invisible man]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/74fixed.png',
    },
    {
        title: 'Bomb',
        entity: '/:075',
        meaning: '[Bomb]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/75fixed.png',
    },
    {
        title: 'Scream',
        entity: '/:076',
        meaning: '[Scream]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/76fixed.png',
    },
    {
        title: 'Beautiful girl',
        entity: '/:077',
        meaning: '[Beautiful girl]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/77fixed.png',
    },
    {
        title: 'Handsome boy',
        entity: '/:078',
        meaning: '[Handsome boy]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/78fixed.png',
    },
    {
        title: 'Fortune cat',
        entity: '/:079',
        meaning: '[Fortune cat]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/79fixed.png',
    },
    {
        title: 'Deal',
        entity: '/:080',
        meaning: '[Deal]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/80fixed.png',
    },
    {
        title: 'Handclap',
        entity: '/:081',
        meaning: '[Handclap]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/81fixed.png',
    },
    {
        title: 'Handshake',
        entity: '/:082',
        meaning: '[Handshake]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/82fixed.png',
    },
    {
        title: 'Lips',
        entity: '/:083',
        meaning: '[Lips]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/83fixed.png',
    },
    {
        title: 'Rose',
        entity: '/:084',
        meaning: '[Rose]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/84fixed.png',
    },
    {
        title: 'Wither',
        entity: '/:085',
        meaning: '[Wither]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/85fixed.png',
    },
    {
        title: 'Heart',
        entity: '/:086',
        meaning: '[Heart]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/86fixed.png',
    },
    {
        title: 'Heartbreak',
        entity: '/:087',
        meaning: '[Heartbreak]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/87fixed.png',
    },
    {
        title: 'Money',
        entity: '/:088',
        meaning: '[Money]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/88fixed.png',
    },
    {
        title: 'Shopping',
        entity: '/:089',
        meaning: '[Shopping]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/89fixed.png',
    },
    {
        title: 'Gift',
        entity: '/:090',
        meaning: '[Gift]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/90fixed.png',
    },
    {
        title: 'Email',
        entity: '/:091',
        meaning: '[Email]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/91fixed.png',
    },
    {
        title: 'Phone',
        entity: '/:092',
        meaning: '[Phone]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/92fixed.png',
    },
    {
        title: 'Cheers',
        entity: '/:093',
        meaning: '[Cheers]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/93fixed.png',
    },
    {
        title: 'Clock',
        entity: '/:094',
        meaning: '[Clock]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/94fixed.png',
    },
    {
        title: 'Waiting',
        entity: '/:095',
        meaning: '[Waiting]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/95fixed.png',
    },
    {
        title: 'Late',
        entity: '/:096',
        meaning: '[Late]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/96fixed.png',
    },
    {
        title: 'Plane',
        entity: '/:097',
        meaning: '[Plane]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/97fixed.png',
    },
    {
        title: 'Alipay',
        entity: '/:098',
        meaning: '[Alipay]',
        src: 'https://ae01.alicdn.com/wimg/common/single/emotions/98fixed.png',
    },
];
export default emotionData;
